### ISSUE TITLE
please tag a new release when you add a sbt version

### ISSUE THREAD

**Issue by hakamadare** [mazgi/sbtenv#19]
Hello!  I'm the maintainer of the sbtenv Homebrew package (https://github.com/Homebrew/homebrew/blob/1777fc04b5afbc1ed309361c1324cfe62ce32f62/Library/Formula/sbtenv.rb).  Because Homebrew prefers to package versioned releases with downloadable tarballs, it would be much easier for me to keep the sbtenv package up to date if you would tag a new point release when you add support for a new sbt version.  Thanks!

-steve

**Comment by mazgi** [comment]
Thanks for your request!
Version 0.0.9 has just been tagged now :)
